name: Update Github README
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Update README
        run: |-
          python omikuji.py
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.name "Omikuji Bot"
          git add -A
          git commit -m "Update Omikuji" || exit 0
          git push
