name: Update Github README

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Update Omikuji
        run: |-
          python omikuji.py
          cat README.md
      - name: Update contribution
        uses: yoshi389111/github-profile-3d-contrib@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.name "README Bot"
          git add -A
          git commit -m "Update README" || exit 0
          git push
